leahneukirchen/xtools

- xlint
Backticks may appear as e.g. [sed search patterns](https://travis-ci.org/voidlinux/void-packages/jobs/68880668) and should be ignored in that case.
Is the regex ok?
> xlint: don't complain for escaped backticks

- xlint
Perl itself is found on `http://cpan.org/src/…` and thus can not use $CPAN_SITE.
> xlint: $CPAN_SITE only for /modules/by-module

- xlint
`python_versions` was removed in https://github.com/voidlinux/void-packages/commit/4e6576e7a4d11e717ce6e16121bbb1bdb362bb50
`python_version` was added in https://github.com/voidlinux/void-packages/commit/29c37543cf75436b4c602fd1a0f16a11b3c05539
> xlint: allow python_version

- xlint
AGPL needs to be vlicensed in templates
> 17:43 < Vaelatern> since GPL doesn't customize the license per-project and we have a copy of the GPL on every void system
> 17:43 < nilsson> does that include the AGPL?
> 17:43 < maldridge> no, AGPL needs to be vlicensed
> 17:43 < maldridge> since its a toxic copyright
> 17:43 < nilsson> k, thanks
> 17:44 < north1> xlint should warn you if it needs vlicense
> xlint: require use of vlicense for AGPL

- xlint
> xlint: correct pycompile_* variables order

- xpcdeps
example of problematic behaivour:
$ xpcdeps uhd
will match
gnuradio-uhd.pc from gnuradio
and wrongly tell us that
gnuradio-devel is a dependency due to Requires: gnuradio-runtime
> xpcdeps: start matching pkg-config files by the slash

- xlint
Added to the go build style, so this ought to be supported.
> xlint: Handle go_mod_mode in linting

- xlint
> xlint: recognize archs=, stop caring about noarch= and replace it with

- xlint
Recently all occurrences of noarch=yes have been replaced in a single 2k
line commit.
time to make sure nobody makes that mistake again.
> xlint: remove unrecognized variable.

- xlint
This will add an optional dependency (but recommended) on spdx-licenses-list https://github.com/void-linux/void-packages/pull/10735
> xlint: deal with SPDX licenses.

- xlint
- xnew
xlint want to have archs before wrksrc.
Sync xnew with xlint.
> reorder xnew output

- xlocate
Add a "default" config file to configure xlocate so it won't have to be in your env
> xlocate: add config file

- xgensum
This way, XBPS_HOSTDIR will be used by xbps-src just like XBPS_MASTERDIR.
`-H` can still overwrite it. It's kept for compatibility.
> xgensum: don't fore hostdir path if -H is omitted

- xlint
Fixes false positive on desc_option_nonfree=
The deprecated nonfree=yes was removed from all templates so this check
is not needed anymore
> xlint: remove nonfree= check

- xlint
- xtools.1
Makes it possible to call xlint as: `xlint 0ad`.
> xlint: accept pkgname as well as path to template.

- xlint
X11 is a derivative of the MIT license and contains the same license
installation requirements.
> xlint: add X11 to the list of vlicense-required licenses

- xlint
Existing accounts should keep their name.
False positives removed from templates at https://github.com/Chocimier/void-packages-org/commit/de94df7c3a26e366c1ad2b9e5675c864a3bd9913
> xlint: check system_accounts underscore prefix

- xlint
This commit introduces two new uses of xlint:
$ xlint :PKGNAME
Lints the template corresponding to package PKGNAME as currently
staged in the git index (i.e. the version that would be committed)
$ xlint :
Lints all templates that are changed in the git index.
Useful to run from the pre-commit hook for the void-packages repo.
> xlint: add option to lint from git index

- README
- xlint
- xtools.1
- do not leak $tmpfile in output from scan()
- indent using tabs
- add new options to README
> xlint: improvements to lint from git index

- xlint
In scan() I was using $argument in the sed script, but oftentimes
$arguments is a path including slashes which breaks havoc.
Different way now, hopefully this is correct now. Note that $msg has to
go through sed since some messages use `\2` to show the matching line.
@leahneukirchen: sorry I screwed this up, I hope everything works fine now!
> xlint: fix bug in previous commit

- xpkgdiff
If the user would like to run a diff for a package on a certain arch, `XBPS_TARGET_ARCH=other-arch xpkgdiff -f foo` will now work properly, even if the user does not have a local repodata for that arch already.
This also allows xpkgdiff to work for all parts of the build matrix in void-packages' CI.
> xpkgdiff: run an in-memory sync to allow use of XBPS_TARGET_ARCH

- xlint
This is a slightly naïve solution that does not check if `$pkgname` matches the template's directory. That would not be very trivial to do to work with the git index functionality or subpackages, and I'm not quite sure how to handle that.
Tested by putting two `$pkgname` and `$version` definitions in a template.
Before:
```
$ xlint chezmoi
grep: the -P option only supports a single pattern
chezmoi'
chezmoi: 'pkgname' defined more than once
chezmoi: 'version' defined more than once
chezmoi: Place license= after pkgname=
chezmoi: Place maintainer= after version=
chezmoi:1: Header should be: # Template file for 'chezmoi
chezmoi:4: revision does not appear immediately after version
```
After:
```
$ xlint chezmoi
chezmoi: 'pkgname' defined more than once
chezmoi: 'version' defined more than …
```
> xlint: deduplicate $pkgname and $version

- xlint
bug introduced in 8c0e21060fd0abdb16c10d62a56ead0a4da75062
> xlint: fix lints broken by extra sed

- xlint
- use awk because scan (grep) does not work over multiple lines
- finds the opening and closing of a variable definition, then checks if it's on the first line and, if not, checks if the first characters are not <space><:graph:>
- checks both single- and double-quoted strings, in a loop because shell makes that hard
- detects lines in multi-line strings that end in a backslash
- `| sort -u -k2` so it does not spam, similar to the other indent lint
- This does sometimes overlap with the "please indent with tabs" and "bad indentation" lints. **Can that be solved somehow? Should it?**
tested by adding this to a template:
```bash
_foo="
bar"
_yo="ahsjdfhsdfj
fsdjhfsdjf"
_blah="asdfsf sdfjhsjhdf
asjhdfjhsdfjhsdfjhd"
_bar="asdfhjsdfj
sdjhfhsjdfhj"
_baz="asdfhjasdjhfsdj
asdjhfdjh" …
```
> xlint: lint multi-line value indentation

- xpkgdiff
the tempdir would be left if there was an error before this
> xpkgdiff: clean up even on error

- _xtools
- xpkgdiff
- xtools.1
adds `-R` and `-a` to make it easier to handle cross, but still support setting `XBPS_TARGET_ARCH` directly.
> xpkgdiff: improve cross functionality

- xrevbump
- xtools.1
- commit all tracked files in srcpkgs/$pkgname/ instead of just template
- don't increment revision if the user has already done it
- this also handles cases where committing fails, which now prints a message (two failure modes I have encountered: commit signing fails, pre-commit hook fails (I run `xlint` in one))
- allow addition of flags to the `git commit` invocation with `xrevbump MESSAGE TEMPLATES... -- COMMIT_ARGS`
- use more bashisms to make things a bit neater
- update manpage/usage
> xrevbump: various improvements

- xlocate
restores old behaviour if `column(1)` is not available
noticed in CI: https://github.com/void-linux/void-packages/issues/40287
> xlocate: handle lack of column(1) gracefully

- xchroot
It seems to work with a relative path, so I am not sure why it requires an absolute path. This way it's much more user friendly.
> xchroot: do not require absolute path

- xnew
$pkgname is not constant, it can change when the package is renamed downstream while we would expect it to still build from the correct sources.
It also often doesn't save any characters and not using the variable makes prettier, simpler URLs that can often be copied from the template without manually replacing variables to get to the page with sources.
Closes #267
> xnew: don't use $pkgname in $distfiles

- xmksv
man vlogger :
```
-f file  Read lines from the specified file.  This option cannot be combine message arguments.
-p pri   The.  pri can be facility.level or just facility.  See FACILITIES, LEVELS or syslog(3).  The default is “user.notice”.
```
`-p` is the correct arg. `-f` does not work
> Update xmksv: change vlogger arg -f to -p

- xdiff
if user run `xdiff --help` , `--help` gets passed to find as an arg, it will cause infinite vimdiff instance coming out, has to kill xdiff's pid to stop it.
> xdiff : make sure $DIR is valid

- _xtools
- xchangelog
- use mdless to render markdown files if mdcat is installed
- xchangelog was missing from the `compdef` header
- use -L for curl to follow redirects
> xchangelog improvements/fixes

- xmypkgs
xmypkgs would get the wrong email for me if run from outside void-packages
> xmypkgs: use git -C $XDISTDIR

- xlint
this is painful:
```
distfiles="https://crates.io/api/v1/crates/pkgname/${version}/download>pkgname-${version}.tar.gz"
```
this is better, and xbps-src already supports extracting them:
```
distfiles="https://static.crates.io/crates/pkgname/pkgname-${version}.crate"
```
this replaces void-linux/void-packages#43417 as it adding new `_SITE` variables has been discouraged
> xlint: lint crates.io distfile urls

- README
- xnews
- xtools.1
employs a mechanism similar to xilog to get packages in installed order, then gets the install message for each in that order.
can be filtered by a pattern in the same method as xilog.
maybe there's a bit more efficient way to do this than a subshell + loop file i/o, but I don't see it
will be even more useful when install messages are only for actual news (https://github.com/void-linux/void-packages/pull/44273)
> new tool: xnews

- README
- xlocate
- xtools.1
implemented what I thought would be useful and made sense, namely:
- `-E, --extended-regexp`
- `-F, --fixed-strings`
- `-G, --basic-regexp`
- `-P, --perl-regexp`
- `-i, --ignore-case`
- `-w, --word-regexp`
This will also allow for someone with `grep.patternType` or `grep.extendedRegexp` set in git's config to change the pattern type.
closes #197
fixes #175
> xlocate: add ability to pass certain flags to git grep

- xpkgdiff
bootstrap packages couldn't be compared, e.g. [this CI run](https://github.com/void-linux/void-packages/actions/runs/6515880414/job/17698786192?pr=46484#step:9:1)
> xpkgdiff: add bootstrap repo

- xlint
these are the only messages that don't have a line number associated with them, adding complexity when parsing the output of xlint.
- `'$var' missing!` only really makes sense with line number 1, as there is not really any other place to put it
- `'$var' defined more than once` I decided to put on the *last* instance of the variable, and add a hint to where the previous definition(s) are
```
$ xlint chezmoi
chezmoi:4: revision does not appear immediately after version
chezmoi:31: 'version' defined more than once: previously on line(s) 3, 25
```
> xlint: improve missing/multiply defined messages

- xlg
only applies on ttys, and i think should respect user preferences
> xlg: add automatic colours

- xlint
This changes makes xlint gracefully accept full SPDX licence expressions, while still evaluating only the individual licences in xlint.
See void-linux/void-packages#48303
> xlint: accept full SPDX licence expressions

- xgensum
- xtools.1
packages like [`vivaldi`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/vivaldi/template) have per-architecture distfiles, which means the philosophy of choosing the first/native architecture won't work.
This allows for specifying a specific architecture to generate the checksum as, instead of autodetecting.
This is not compatible with `-i` currently (and even without, the `sed` output is wrong), but it'd be nice to support that. Not sure what the best approach would be...
> xgensum: support explicitly specifying architecture

- README
- xdeptree
- xtools.1
uses `tree(1)` to generate a true tree of a package's dependencies (unlike `xbps-query --fulldeptree -x`, which just generates a list from the tree)
```
$ xdeptree chezmoi
.
└── chezmoi
└── glibc
└── libxcrypt-compat
```
limit the output depth:
```
$ xdeptree -L 3 -R python
.
└── python
└── python2
├── bzip2
│   └── glibc
├── ca-certificates
│   ├── openssl
│   └── run-parts
├── expat
│   └── glibc
├── gdbm
│   └── glibc
├── glibc
│   └── libxcrypt-compat
├── libcrypto3
│   └── glibc
├── libffi
│   └── glibc
├── libreadline8
│   ├── glibc
│   └── ncurses-libs
├── libssl3
│   └── glibc
├── libxcrypt
│   └── glibc
├── ncurses-libs
│   └── glibc
├── sqlite
│   ├── glibc
│   ├── libedit
│   └── zlib
└── zlib
└── glibc
```
> new tool: xdeptree
